# Generated by Django 3.2.13 on 2022-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_auto_20220423_0553'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='users', to='checkins.Team'),
        ),
    ]
