# Generated by Django 3.2.13 on 2022-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('emotion', models.CharField(max_length=255, null=True)),
                ('platform', models.PositiveIntegerField(choices=[('Slack', 1)], default=1)),
                ('color', models.PositiveIntegerField(choices=[('Red', 1), ('Yellow', 2), ('Green', 3)])),
                ('organization', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('team', models.CharField(max_length=255, verbose_name='Team Name')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
