# Generated by Django 3.2.13 on 2022-04-23 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='username',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='color',
            field=models.PositiveIntegerField(choices=[(1, 'Red'), (2, 'Yellow'), (3, 'Green')]),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkins.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkins.team'),
        ),
    ]
